/**
 * Normalizes an extension object from Microsoft Marketplace to a simplified, consistent format.
 * @param {Object} marketplaceExt The extension object from Microsoft Marketplace.
 * @returns {Object} The normalized extension object.
 */
function normalizeMarketplaceExtension(marketplaceExt) {
    if (!marketplaceExt || !marketplaceExt.versions || marketplaceExt.versions.length === 0) {
        return null;
    }

    const latestVersion = marketplaceExt.versions[0];
    const publisher = marketplaceExt.publisher.publisherName;
    const name = marketplaceExt.extensionName;
    const uniqueId = `${publisher}.${name}`;

    // Extract necessary metadata to match the required VSCode schema structure
    const normalized = {
        // Unique identifier for deduplication
        uniqueId: uniqueId,
        // Source for prioritization
        source: 'marketplace',
        // Basic info
        publisher: {
            publisherId: marketplaceExt.publisher.publisherId,
            publisherName: publisher,
            displayName: marketplaceExt.publisher.displayName
        },
        extensionId: marketplaceExt.extensionId,
        extensionName: name,
        displayName: marketplaceExt.displayName,
        shortDescription: marketplaceExt.shortDescription,
        // Version info
        version: latestVersion.version,
        lastUpdated: latestVersion.lastUpdated,
        // Statistics (e.g., install count)
        statistics: marketplaceExt.statistics,
        // VSIX download info (URL will be generated by the proxy route)
        downloadUrl: `/gallery/download/${publisher}/${name}/${latestVersion.version}`,
        // Raw data for full detail endpoint
        raw: marketplaceExt
    };

    return normalized;
}

/**
 * Normalizes an extension object from Open VSX to a simplified, consistent format.
 * @param {Object} openvsxExt The extension object from Open VSX.
 * @returns {Object} The normalized extension object.
 */
function normalizeOpenVSXExtension(openvsxExt) {
    if (!openvsxExt || !openvsxExt.version) {
        return null;
    }

    const publisher = openvsxExt.namespace;
    const name = openvsxExt.name;
    const uniqueId = `${publisher}.${name}`;

    // Map Open VSX fields to the Marketplace-like structure
    const normalized = {
        // Unique identifier for deduplication
        uniqueId: uniqueId,
        // Source for prioritization
        source: 'openvsx',
        // Basic info
        publisher: {
            publisherId: openvsxExt.namespace, // Using namespace as ID for simplicity
            publisherName: publisher,
            displayName: openvsxExt.namespace // Open VSX often lacks a separate display name for publisher
        },
        extensionId: openvsxExt.uuid, // Using UUID as ID
        extensionName: name,
        displayName: openvsxExt.displayName || name,
        shortDescription: openvsxExt.description,
        // Version info
        version: openvsxExt.version,
        lastUpdated: openvsxExt.timestamp,
        // Statistics (Open VSX uses 'downloadCount')
        statistics: [{
            statisticName: 'install',
            value: openvsxExt.downloadCount || 0
        }],
        // VSIX download info (URL will be generated by the proxy route)
        downloadUrl: `/gallery/download/${publisher}/${name}/${openvsxExt.version}`,
        // Raw data for full detail endpoint
        raw: openvsxExt
    };

    return normalized;
}

/**
 * Aggregates and deduplicates a list of normalized extensions.
 * Prioritization: Marketplace > Open VSX.
 * @param {Array<Object>} extensions A list of normalized extension objects.
 * @returns {Array<Object>} The aggregated, deduplicated, and prioritized list.
 */
function aggregateAndDeduplicate(extensions) {
    const uniqueExtensions = new Map();

    // 1. Collect all extensions, prioritizing Marketplace over Open VSX
    for (const ext of extensions) {
        if (!ext || !ext.uniqueId) continue;

        const existing = uniqueExtensions.get(ext.uniqueId);

        if (!existing) {
            // First time seeing this extension
            uniqueExtensions.set(ext.uniqueId, ext);
        } else if (ext.source === 'marketplace' && existing.source !== 'marketplace') {
            // Found a Marketplace version, which has higher priority
            uniqueExtensions.set(ext.uniqueId, ext);
        }
        // If existing is Marketplace and new is Open VSX, keep existing (higher priority)
        // If both are the same source, keep the one that came first (doesn't matter much)
    }

    // 2. Convert map values back to an array
    let finalExtensions = Array.from(uniqueExtensions.values());

    // 3. Sort by priority (Marketplace first) and then by install count (descending)
    finalExtensions.sort((a, b) => {
        // Priority: Marketplace (0) > Open VSX (1)
        const priorityA = a.source === 'marketplace' ? 0 : 1;
        const priorityB = b.source === 'marketplace' ? 0 : 1;

        if (priorityA !== priorityB) {
            return priorityA - priorityB;
        }

        // Secondary sort: Install count (descending)
        const installsA = (a.statistics || []).find(s => s.statisticName === 'install')?.value || 0;
        const installsB = (b.statistics || []).find(s => s.statisticName === 'install')?.value || 0;

        return installsB - installsA;
    });

    return finalExtensions;
}

module.exports = {
    normalizeMarketplaceExtension,
    normalizeOpenVSXExtension,
    aggregateAndDeduplicate
};
